import type { NextPage } from 'next'
import Head from 'next/head'


import homeStyles from '../styles/Home.module.css'
import headerStyles from '../styles/Header.module.css'
import footerStyles from '../styles/Footer.module.css'

import {getUserInfo} from '../lib/user';
import Card from '../components/card';

const Header: NextPage = () => {
  return (
    <div className={headerStyles.container}>
      <h2>Amazing header</h2>
      <span>Additional content</span>
    </div>
  );
};

type FooterProps = {
    link1: string;
    link2: string;
}

const Footer: NextPage<FooterProps> = ({link1, link2}) => {
  return (
    <footer className={footerStyles.container}>
      <h2>Footer section</h2>
      <div className={footerStyles.links}>
        <a href={link1}>Link1</a>
        <a href={link2}>Link2</a>
      </div>
    </footer>
  );
};

type HomeProps = {
    name: string;
    discount: number;
}

const Home: NextPage<HomeProps> = (userInfo) => {
  return (
    <div className={homeStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className={homeStyles.main}>
        <Card name={userInfo.name} discount={userInfo.discount}/>
      </main>

      <Footer link1="1" link2="2" />
    </div>
  )
}

export const getStaticProps = async () => {
  const userInfo = await getUserInfo()
  return {
    props: userInfo,
  }
}

export default Home
